language: ruby
rvm:
- 2.2.0
script: npm run setup && npm run sass && npm run build-pages && npm run deploy-pages
cache:
  directories:
  - bower_components
  - node_modules
  - vendor/bundle
env:
  global:
    secure: jOar8QY2ST1nwoNe6Vt8teqTggB9A6MpCWdcmlwCohYwql4j2vrcLgIQP+dsnVGCoXi1ydszWouO4N6R0TzgOtNSSHpOqgPJP8KpfpbCfMVKSWx6S00yXJyGni3zw6XSvp2b4RgZXjsZp5bUDyy34GHqFZTtfZrT2KoBvdhiQEZ6niHJ59m16uRxzF26mmf03KK9shVwoCIYPjv/t60C+R35qd+s8VpH7Na0LikDiOn3edMC5qPagJ3ZeadivdSJDGnQHt1NNBrTN6vVSj71pIfi/ampshhM5prJNMsOo+cTVSiSxhkMjI0CzQn78f9CbRAL/sOOswxnmdFiwKLz32Q7igK8oPvje+4a+IYIJRgaM3gq4D76ArPIfxI/ggRfHqRI9m8MgHLdDycbIDIIPNRgPZeLyn87DsTXORRfIUnelMjwolRaN49VLdSq5JeA6iDXqETG0EQN56aJ/1iYaU3QdHe/5K4h9iiBWE3A8pFYfHhdJx41RInantBXGcWxP/B/obQf7PBt6QjAwojHIu22mWsmSlH7buzuHvEkN9enUoIJYudkTZafj1/F1gdCy7jRbGKngsEz99xJJHOoo0l7mBYVTbo4mP5D8mbwI+VeQQK2tYAN1SPAS8DSn3hLbJ3OkYe0FQGF1s1AQgOvDJtfhtv+aAgeJdCzaZoV/+s=
